#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyNotification.Resource", IsApplication=true)]

namespace MyNotification
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baba = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baby = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HappyBaby = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mother = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Mybaby = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int NewBornBaby = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnRandom = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnSet = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int btnSetting = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int btnTheme = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int img1 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int img2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int img3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int img4 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int img5 = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int llRaadio = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int llTime = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int scrollView1 = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int timePicker = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int alarm_controller = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SecondLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ThemeLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int babySound = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int TimeText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
